;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        org-self-insert-command
        prelude-kill-whole-line
        winner-undo
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        easy-mark
        haml-electric-backspace
        prelude-github
        prelude-move-beginning-of-line
        smex
        ))
